version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio
    container_name: portfolio
    env_file:
      - .env.local
    environment:
      - WORDS_JSON_PATH=/app/data/words.json
      - WORDS_AI_JSON_PATH=/app/data/words_ai.json
      - OCR_RESULTS_PATH=/app/data/ocr-results.json
    volumes:
      - /volume1/docker/data:/app/data
    ports:
      - '3000:3000'
